name: Make Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v3.0.0)"
        required: true
        type: string
      description:
        description: "Release description / Changelog (Optional)"
        required: false
        type: string
        default: ""

permissions:
  contents: write
  actions: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract Mod Info
        id: mod_info
        run: |
          MOD_DISPLAY_NAME=$(jq -r '.displayName' mod.json)
          MOD_DISPLAY_NAME_CLEAN=$(echo "$MOD_DISPLAY_NAME" | tr -d ' ')
          ARTIFACT_NAME="${MOD_DISPLAY_NAME_CLEAN} (in a box)"

          CLEAN_VERSION=$(echo "${{ inputs.version }}" | sed 's/^v//')
          DEXED_JAR_NAME="Aquarion-${CLEAN_VERSION}.jar"

          echo "dexed_jar_name=${DEXED_JAR_NAME}" >> $GITHUB_OUTPUT
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Download built artifact from Java CI
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          name: ${{ steps.mod_info.outputs.artifact_name }}
          path: ./downloaded_artifact

      - name: Rename file inside artifact folder
        run: |
          cd ./downloaded_artifact
          ORIGINAL_FILE=$(ls *.jar | head -n 1)
          mv "$ORIGINAL_FILE" "${{ steps.mod_info.outputs.dexed_jar_name }}"

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.description }}
          generate_release_notes: true
          files: ./downloaded_artifact/${{ steps.mod_info.outputs.dexed_jar_name }}
